### ISSUE TITLE
Deploy your website to GitHub pages

### ISSUE THREAD

**Issue by smakosh** [Jee-El/jee-el.github.io#1]
You can follow this guide: https://www.freecodecamp.org/news/hosting-custom-domain-on-github-pages-8c598248d2bc/ or https://www.pluralsight.com/guides/how-to-host-your-static-webpages-on-github-pages

**Comment by Jee-El** [comment]
> You can follow this guide: https://www.freecodecamp.org/news/hosting-custom-domain-on-github-pages-8c598248d2bc/ or https://www.pluralsight.com/guides/how-to-host-your-static-webpages-on-github-pages

I've already done that but I forgot to add it to the repo's about section xd, it should be fine now
